name: Tests

on:
    push:
    pull_request:

jobs:
    debug-dev-config:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2

            -   name: Cache Composer packages
                id: composer-cache
                uses: actions/cache@v2
                with:
                    path: vendor
                    key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
                    restore-keys: |
                        ${{ runner.os }}-php-

            -   name: Install php dependencies
                uses: php-actions/composer@v6

            -   name: Run console to debug config
                run: php bin/console debug:config artprima_prometheus_metrics

    debug-test-config:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2

            -   name: Cache Composer packages
                id: composer-cache
                uses: actions/cache@v2
                with:
                    path: vendor
                    key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
                    restore-keys: |
                        ${{ runner.os }}-php-

            -   name: Install php dependencies
                uses: php-actions/composer@v6

            -   name: Run console to debug config
                run: php bin/console debug:config --env=test artprima_prometheus_metrics
